import { Injectable } from '@angular/core';
import { DocumentSnapshot } from '@firebase/firestore';
import { Block, createBlock, createAction, Action, createDocumentMeta } from '@blockframes/model';
import { AuthService } from '@blockframes/auth/service';
import { BlockframesSubCollection } from '@blockframes/utils/abstract-service';

@Injectable({ providedIn: 'root' })
export class BlockService extends BlockframesSubCollection<Block> {
  readonly path = 'waterfall/:waterfallId/blocks';

  constructor(
    private authService: AuthService,
  ) {
    super();
  }

  protected override fromFirestore(snapshot: DocumentSnapshot<Block>) {
    if (!snapshot.exists()) return undefined;
    const block = super.fromFirestore(snapshot);
    return createBlock(block);
  }

  public create(waterfallId: string, name: string, actions: Partial<Action>[], blockDate: Date) {
    const createdBy = this.authService.uid;
    const block = createBlock({
      _meta: createDocumentMeta({ createdBy }),
      timestamp: blockDate.getTime(),
      name
    });
    let index = 0;
    for (const action of actions) {
      block.actions[index] = createAction({
        ...action,
        actionId: index.toString() // overwrite previous id generated by action() in libs/model/src/lib/waterfall/action.ts
      });
      index++;
    }

    return this.add(block, { params: { waterfallId } });
  }

  public async history(waterfallId: string, ids: string[], fromId?: string) {
    const blocks = await this.getValue(ids, { waterfallId });
    return fromId ? blocks.slice(0, ids.indexOf(fromId) + 1) : blocks;
  }

}
