import {
  Territory,
  TerritoryISOA2,
  TerritoryISOA2Value,
  TerritoryISOA3,
  TerritoryISOA3Value
} from './types'

export const contractStatus = {
  accepted: 'Accepted',
  paid: 'Paid',
  unknown: 'Unknown',
  waitingsignature: 'Waiting for signature',
  waitingpayment: 'Waiting for payment',
  rejected: 'Rejected',
  aborted: 'Aborted',
  /**
   * @dev first status of a contract
   * Starting from this status, the contract is visible by creator only
   */
  draft: 'Draft',
  /**
   * @dev once the user hit the submit button, the contract is waiting for approvment
   * Starting from this status, the contract is visible by creator (but not editable anymore) and by admins
   */
  submitted: 'Submitted',
  /**
   * @dev when an admin checked a "submitted" contract and all seems good.
   * Starting from this status, contract is visible for every parties
   */
  undernegotiation: 'Under negotiation',
} as const

export const contractType = {
  mandate: 'Mandate',
  sale: 'Sale'
} as const

export const legalDocumentTypes = {
  chain_of_titles: 'Chain of titles',
  invoices: 'Invoices'
} as const

export const legalRoles = {
  undefined: 'Undefined role',
  serviceProvider: 'Service provider', // service-provider
  licensor: 'Licensor',
  licensee: 'Licensee',
  seller: 'Seller',
  lender: 'Lender',
  promisor: 'Promisor',
  promisee: 'Promisee',
  beneficiary: 'Beneficiary',
  thirdParty: 'Third party', // third-party
  purchaser: 'Purchaser'
} as const

export const subLicensorRoles = {
  signatory: 'Signatory',
  observator: 'Observator'
} as const

export const licenseStatus = {
  unknown: 'unknown',
  undernegotiation: 'under negotiation',
  waitingsignature: 'waiting for signature',
  waitingpayment: 'waiting for paiment',
  paid: 'paid'
} as const

export const distributionRightStatus = {
  /**
   * @dev first status of a right
   * Starting from this status, the right is visible by creator only
   */
  draft: 'Draft',

  /**
   * @dev first status of a right
   * Starting from this status, the right is visible by creator only
   */
  cart: 'In cart',

  /**
   * @dev the right have been sold
   */
  sold: 'Sold',

  /**
   * @dev in this status, a contract should exists regarding this distribution right.
   * When Contract status changes, this could change too
   */
  undernegotiation: 'Under negotiation',
} as const

export const certifications = {
  artEssai: 'Art & Essai',
  eof: 'EOF',
  awardedFilm: 'Awarded Film',
  aListCast: 'A-list Cast',
  europeanQualification: 'European Qualification'
} as const

export const colors = {
  c: 'Color',
  b: 'Black & white',
  colorBW: 'Color & Black & White'
} as const

export const contentType = {
  feature_film: 'Feature Film',
  short: 'Short Film',
  serie: 'Tv Serie',
  season: 'Season',
  volume: 'Volume',
  episode: 'Episode',
  collection: 'Collection',
  tv_film: 'TV Film',
  flow: 'Flow'
}

export const crewRoles = {
  writer: 'Writer',
  scoreComposer: 'Score Composer',
  dialogueWriter: 'Dialogue Writer',
  photographyDirector: 'Director of Photography',
  editor: 'Editor',
  castingDirector: 'Casting Director',
  artisticDirector: 'Artistic Director',
  costumeDesigner: 'Costume Designer',
  makeUpArtist: 'Make-Up Artist',
  productionDesigner: 'Production Designer',
  firstAssistantDirector: '1st Assistant Director',
  secondAssistantDirector: '2nd Assistant Director',
  postProductionDirector: 'Post-Production Director',
  originalAuthor: 'Original Author'
} as const

export const directorCategory = {
  firstFeature: 'First Feature',
  risingTalent: 'Rising Talent',
  confirmed: 'Confirmed Director',
  prestige: 'Prestige'
} as const

export const genres = {
  comedy: 'Comedy',
  drama: 'Drama',
  action: 'Action',
  horror: 'Horror',
  scienceFiction: 'Science Fiction', // science-fiction
  thriller: 'Thriller',
  comingAge: 'Young Adult', // coming-of-age
  fantasy: 'Fantasy',
  romance: 'Romance',
  western: 'Western',
  periodPiece: 'Period Piece', // period-piece
  adventure: 'Adventure',
  biography: 'Biography',
  war: 'War',
  police: 'Police',
  animation: 'Animation',
  documentary: 'Documentary',
  erotic: 'Erotic',
  tvShow: 'TV Show', //tv-show
  webSeries: 'Web Series', //web-series
  virtualReality: 'Virtual Reality', // virtual-reality
  family: 'Family',
} as const

export const hostedVideoTypes = {
  tailer: 'Trailer',
  teaser: 'Teaser',
  reel: 'Reel',
  clip: 'Clip',
  pitch: 'Pitch',
} as const

// @TODO (#1658) Update LANGUAGES static model to be RFC-5646 compliant
export const languages = {
  all: 'All languages',
  albanian: 'Albanian',
  arabic: 'Arabic',
  armenian: 'Armenian',
  azerbaijani: 'Azerbaijani',
  bambara: 'Bambara',
  basque: 'Basque',
  belarussian: 'Belarussian',
  bengali: 'Bengali',
  bosnian: 'Bosnian',
  bulgarian: 'Bulgarian',
  burmese: 'Burmese',
  cantonese: 'Cantonese',
  catalan: 'Catalan',
  croatian: 'Croatian',
  czech: 'Czech',
  danish: 'Danish',
  dutch: 'Dutch',
  english: 'English',
  estonian: 'Estonian',
  filipino: 'Filipino',
  finnish: 'Finnish',
  flemish: 'Flemish',
  french: 'French',
  gaelic: 'Gaelic',
  galician: 'Galician',
  georgian: 'Georgian',
  german: 'German',
  greek: 'Greek',
  gujarati: 'Gujarati',
  hebrew: 'Hebrew',
  hindi: 'Hindi',
  hungarian: 'Hungarian',
  icelandic: 'Icelandic',
  indonesian: 'Indonesian',
  italian: 'Italian',
  japanese: 'Japanese',
  javanese: 'Javanese',
  kannada: 'Kannada',
  kazakh: 'Kazakh',
  khmer: 'Khmer',
  korean: 'Korean',
  kosovan: 'Kosovan',
  kurdish: 'Kurdish',
  kyrgyz: 'Kyrgyz',
  laotian: 'Laotian',
  latvian: 'Latvian',
  lingala: 'Lingala',
  lithuanian: 'Lithuanian',
  macedonian: 'Macedonian',
  malayalam: 'Malayalam',
  maltese: 'Maltese',
  'mandarin-chinese': 'Mandarin Chinese',
  marathi: 'Marathi',
  moldavian: 'Moldavian',
  montenegrin: 'Montenegrin',
  norwegian: 'Norwegian',
  oriya: 'Oriya',
  panjabi: 'Panjabi',
  persian: 'Persian',
  polish: 'Polish',
  portuguese: 'Portuguese',
  romanian: 'Romanian',
  russian: 'Russian',
  serbian: 'Serbian',
  slovak: 'Slovak',
  slovene: 'Slovene',
  spanish: 'Spanish',
  swahili: 'Swahili',
  swedish: 'Swedish',
  tajiki: 'Tajiki',
  tamil: 'Tamil',
  telugu: 'Telugu',
  tetum: 'Tetum',
  thai: 'Thai',
  turkish: 'Turkish',
  turkmen: 'Turkmen',
  ukrainian: 'Ukrainian',
  urdu: 'Urdu',
  uzbek: 'Uzbek',
  valencian: 'Valencian',
  vietnamese: 'Vietnamese',
  welsh: 'Welsh'
} as const

export const medias = {
  payTv: 'Pay TV', // pay-tv
  freeTv: 'Free TV', // free-tv
  payPerView: 'Pay Per View', // pay-per-view
  est: 'EST',
  nVod: 'N-VOD', // n-vod
  aVod: 'A-VOD', // a-vod
  fVod: 'F-VOD', // f-vod
  sVod: 'S-VOD', // s-vod
  theatrical: 'Theatrical',
  video: 'Video',
  planes: 'Planes',
  boats: 'Boats',
  hotels: 'Hotels',
} as const

export const memberStatus = {
  confirmed: 'Confirmed',
  looselyAttached: 'Loosely Attached',
  target: 'Target'
} as const

export const movieCurrencies = {
  USD: 'US Dollar',
  EUR: 'Euro',
  JPY: 'Japanese Yen',
  GBP: 'Pound Sterling',
  AUD: 'Australian Dollar',
  CAD: 'Canadian Dollar',
  CHF: 'Swiss Franc',
  CNY: 'Chinese Renminbi',
  SEK: 'Swedish Krona',
  NZD: 'New Zealand Dollar'
} as const

export const movieFormat = {
  '1_33': '1.33',
  '1_37': '1.37',
  '1_66': '1.66',
  '1_77': '1.77',
  '1_85': '1.85',
  scope: 'SCOPE',
  '4/3': '4/3',
  '16/9': '16/9'
} as const

export const movieFormatQuality = {
  sd: 'SD',
  hd: 'HD',
  '2k': '2K',
  '4k': '4K',
  UHD: 'UHD',
  '3D': '3D',
  '3DSD': '3DSD',
  '3DHD': '3DHD',
  '3DUHD': '3DUHD'
} as const

export const movieLanguageTypes = {
  original: 'Original',
  dubbed: 'Dubbings',
  subtitle: 'Subtitles',
  caption: 'Closed Captions',
} as const

export const premiereType = {
  international: 'International',
  world: 'World',
  market: 'Market',
  national: 'National',
} as const

export const producerRoles = {
  executiveProducer: 'Executive Producer',
  lineProducer: 'Line Producer',
  associateProducer: 'Associate Producer',
  productionManager: 'Production Manager'
} as const

export const productionStatus = {
  development: 'In development',
  shooting: 'In Production',
  post_production: 'In Post-production',
  finished: 'Completed',
  released: 'Released'
} as const

export const promotionalElementTypes = {
  trailer: 'Trailer',
  poster: 'Poster',
  banner: 'Banner',
  still_photo: 'Stills',
  presentation_deck: 'Presentation deck',
  scenario: 'Script',
  promo_reel_link: 'Promo reel',
  screener_link: 'Screener',
  trailer_link: 'Trailer',
  teaser_link: 'Teaser',
  moodboard: 'Moodboard'
} as const

export const rating = {
  pegi: 'PEGI',
  csa: 'CSA',
  cnc: 'CNC'
} as const

export const scoring = {
  a: 'A',
  b: 'B',
  c: 'C',
  d: 'D'
} as const

export const screeningStatus = {
  tobedetermined: 'To be determined',
  estimated: 'Estimated',
  confirmed: 'Confirmed'
} as const

export const shootingPeriod = {
  early: 'Early',
  late: 'Late',
  mid: 'Mid',
} as const

export const socialGoals = {
  no_poverty: 'No Poverty',
  hunger: 'Zero Hunger',
  gender_equality: 'Gender Equality',
  sanitation: 'Clean Water / Sanitation',
  well_being: 'Good Health and Well-being',
  education: 'Quality Education',
  clean_energy: 'Affordable and Clean Energy',
  work_and_growth: 'Decent Work and Economic Growth',
  industry: 'Industry, innovation and infrastructure',
  inequalities: 'Reduce inequalities',
  communities: 'Sustainable cities and communities',
  life_on_land: 'Life on land'
} as const

export const soundFormat = {
  mono: 'Mono',
  stereo: 'Stereo',
  dolbySR: 'Dolby SR',
  dts: 'DTS',
  'dolby-5.1': 'Dolby 5.1',
  'dolby-7.1': 'Dolby 7.1',
  thx: 'THX'
} as const

export const stakeholderRoles = {
  executiveProducer: 'Executive Producer',
  coProducer: 'Co-Producer',
  lineProducer: 'Line Producer',
  distributor: 'Distributor',
  salesAgent: 'Sales Agent',
  laboratory: 'Laboratory',
  financier: 'Financier',
  broadcasterCoproducer: 'Broadcaster coproducer'
} as const

export const storeStatus = {
  submitted: 'Submitted',
  accepted: 'Accepted',
  draft: 'Draft',
  refused: 'Refused',
} as const

export const storeType = {
  library: 'Library',
  line_up: 'Line-Up',
} as const;

export const unitBox = {
  usd: 'USD',
  eur: 'EUR',
  admissions: 'Admissions',
} as const

export const cartStatus = {
  pending: 'Pending',
  submitted: 'Submitted',
  accepted: 'Accepted',
  paid: 'Paid'
} as const

export const orgActivity = {
  production: 'Production',
  intlSales: 'International Sales',
  distribution: 'Distribution',
  tvBroadcast: 'Television Broadcast',
  vodPlatform: 'VOD Platform',
  theatricalExhibition: 'Theatrical Exhibition',
  buyersRep: 'Buyer\'s Rep',
  filmFestival: 'Film Festival',
  filmFund: 'Film Fund',
  filmLibrary: 'Film Library',
  filmCommission: 'Film Commission',
  financialInstitution: 'Financial Institution',
  press: 'Press',
  inflight: 'Inflight',
} as const

/** Status of an Organization, set to pending by default when an Organization is created. */
export const organizationStatus = {
  pending: 'Pending',
  accepted: 'Accepted'
} as const

export const festival = {
  cannes: 'Cannes International Film Festival',
  venice: 'Venice International Film Festival',
  berlinale: 'Berlin International Film Festival (The Berlinale)',
  toronto: 'Toronto International Film Festival (TIFF)',
  sundace: 'Sundance Film Festival',
  locarno: 'Locarno International Film Festival',
  rotterdam: 'International Film Festival Rotterdam',
  triBeCa: 'TriBeCa Film Festival',
  sxsw: 'SXSW Film Festival',
  sanSebastian: 'San Sebastian International Film Festival',
  oscar: 'Oscar Academy Awards',
  goldenGlobe: 'Golden Globe Awards',
  bfta: 'BAFTA Film Awards'
} as const

export const territories = {
  world: 'World',
  "aland-islands": "Åland Islands",
  afghanistan: "Afghanistan",
  albania: "Albania",
  algeria: "Algeria",
  "american-samoa": "American Samoa",
  andorra: "Andorra",
  angola: "Angola",
  "anguilla-&-barbuda": "Anguilla",
  antartica: "Antarctica",
  "antigua-and-barbuda": "Antigua and Barbuda",
  argentina: "Argentina",
  armenia: "Armenia",
  aruba: "Aruba",
  australia: "Australia",
  austria: "Austria",
  azerbaijan: "Azerbaijan",
  bahamas: "Bahamas (the)",
  bahrain: "Bahrain",
  bangladesh: "Bangladesh",
  barbados: "Barbados",
  belarus: "Belarus",
  belgium: "Belgium",
  belize: "Belize",
  benin: "Benin",
  bermuda: "Bermuda",
  bhutan: "Bhutan",
  bolivia: "Bolivia (Plurinational State of)",
  bonaire: "Bonaire",
  "sint-eustatius-and-saba": "Sint Eustatius and Saba",
  "bosnia-and-herzegovina": "Bosnia and Herzegovina",
  botswana: "Botswana",
  "bouvet-island": "Bouvet Island",
  brazil: "Brazil",
  "british-indian-ocean-territory": "British Indian Ocean Territory (the)",
  brunei: "Brunei Darussalam",
  bulgaria: "Bulgaria",
  burkina: "Burkina Faso",
  burundi: "Burundi",
  "cabo-verde": "Cabo Verde",
  cambodia: "Cambodia",
  cameroon: "Cameroon",
  canada: "Canada",
  "cayman-islands": "Cayman Islands (the)",
  "central-african-republic": "Central African Republic (the)",
  chad: "Chad",
  chile: "Chile",
  china: "China",
  "christmas- island": "Christmas Island",
  "cocos-islands": "Cocos (Keeling) Islands (the)",
  colombia: "Colombia",
  comoros: "Comoros (the)",
  "congo-democratic-republic": "Congo (the Democratic Republic of the)",
  congo: "Congo (the)",
  "cook-islands": "Cook Islands(the)",
  "costa-rica": "Costa Rica",
  croatia: "Croatia",
  cuba: "Cuba",
  curacao: "Curaçao",
  cyprus: "Cyprus",
  "northern-cyprus": "Turkish Republic of Northern Cyprus",
  czech: "Czechia",
  "cote-d-ivoire": "Côte d'Ivoire",
  denmark: "Denmark",
  djibouti: "Djibouti",
  dominica: "Dominica",
  "dominican-republic": "Dominican Republic (the)",
  ecuador: "Ecuador",
  egypt: "Egypt",
  "el-salvador": "El Salvador",
  "equatorial-guinea": "Equatorial Guinea",
  eritrea: "Eritrea",
  estonia: "Estonia",
  eswatini: "Eswatini",
  ethiopia: "Ethiopia",
  "falkland-islands": "Falkland Islands (the) [Malvinas]",
  "faroe-islands": "Faroe Islands (the)",
  fiji: "Fiji",
  finland: "Finland",
  france: "France",
  "french-guiana": "French Guiana",
  "french-polynesia": "French Polynesia",
  "french-southern-territories": "French Southern Territories (the)",
  gabon: "Gabon",
  gambia: "Gambia(the)",
  georgia: "Georgia",
  germany: "Germany",
  ghana: "Ghana",
  gibraltar: "Gibraltar",
  greece: "Greece",
  greenland: "Greenland",
  grenada: "Grenada",
  guadeloupe: "Guadeloupe",
  guam: "Guam",
  guatemala: "Guatemala",
  guernsey: "Guernsey",
  guinea: "Guinea",
  "guinea-bissau": "Guinea-Bissau",
  guyana: "Guyana",
  haiti: "Haiti",
  "heard-island-and-mcdonald-islands": "Heard Island and McDonald Islands",
  "holy-see": "Holy See (the)",
  "honduras": "Honduras",
  "hong-kong": "Hong Kong",
  hungary: "Hungary",
  "iceland": "Iceland",
  "india": "India",
  "indonesia": "Indonesia",
  iran: "Iran (Islamic Republic of)",
  iraq: "Iraq",
  ireland: "Ireland",
  "isle-of-man": "Isle of Man",
  israel: "Israel",
  italy: "Italy",
  jamaica: "Jamaica",
  japan: "Japan",
  jersey: "Jersey",
  jordan: "Jordan",
  kazakhstan: "Kazakhstan",
  kenya: "Kenya",
  kiribati: "Kiribati",
  "north-korea": "Korea (the Democratic People's Republic of)",
  "south-korea": "Korea (the Republic of)",
  kosovo: "Republic of Kosovo",
  kuwait: "Kuwait",
  kyrgyzstan: "Kyrgyzstan",
  laos: "Lao People's Democratic Republic (the)",
  latvia: "Latvia",
  lebanon: "Lebanon",
  lesotho: "Lesotho",
  liberia: "Liberia",
  libya: "Libya",
  liechtenstein: "Liechtenstein",
  lithuania: "Lithuania",
  luxembourg: "Luxembourg",
  macao: "Macao",
  madagascar: "Madagascar",
  malawi: "Malawi",
  malaysia: "Malaysia",
  maldives: "Maldives",
  mali: "Mali",
  malta: "Malta",
  marshall: "Marshall Islands (the)",
  martinique: "Martinique",
  mauritania: "Mauritania",
  mauritius: "Mauritius",
  mayotte: "Mayotte",
  mexico: "Mexico",
  micronesia: "Micronesia (Federated States of)",
  moldova: "Moldova (the Republic of)",
  monaco: "Monaco",
  mongolia: "Mongolia",
  montenegro: "Montenegro",
  montserrat: "Montserrat",
  morocco: "Morocco",
  mozambique: "Mozambique",
  myanmar: "Myanmar",
  namibia: "Namibia",
  nauru: "Nauru",
  nepal: "Nepal",
  netherlands: "Netherlands(the)",
  "new-caledonia": "New Caledonia",
  "new-zealand": "New Zealand",
  nicaragua: "Nicaragua",
  niger: "Niger (the)",
  nigeria: "Nigeria",
  niue: "Niue",
  "norfolk-island": "Norfolk Island",
  "north-macedonia": "North Macedonia",
  "northern-mariana-islands": "Northern Mariana Islands (the)",
  norway: "Norway",
  "oman": "Oman",
  pakistan: "Pakistan",
  palau: "Palau",
  palestine: "Palestine, State of",
  panama: "Panama",
  papua: "Papua New Guinea",
  paraguay: "Paraguay",
  peru: "Peru",
  philippines: "Philippines(the)",
  pitcairn: "Pitcairn",
  poland: "Poland",
  portugal: "Portugal",
  "puerto-rico": "Puerto Rico",
  qatar: "Qatar",
  romania: "Romania",
  russia: "Russian Federation (the)",
  rwanda: "Rwanda",
  reunion: "Réunion",
  "saint-barthelemy": "Saint Barthélemy",
  "saint-helena-ascension-and-tristan-da-cunha": "Saint Helena, Ascension and Tristan da Cunha",
  "saint-kitts-and-nevis": "Saint Kitts and Nevis",
  "saint-lucia": "Saint Lucia",
  "saint-martin-french": "Saint Martin (French part)",
  "saint-pierre-and-miquelon": "Saint Pierre and Miquelon",
  "saint-vincent-and-the-grenadines": "Saint Vincent and the Grenadines",
  samoa: "Samoa",
  "san-marino": "San Marino",
  "sao-tome-and-principe": "Sao Tome and Principe",
  "saudi-arabia": "Saudi Arabia",
  senegal: "Senegal",
  serbia: "Serbia",
  seychelles: "Seychelles",
  "sierra-leone": "Sierra Leone",
  singapore: "Singapore",
  "saint-martin-dutch": "Sint Maarten (Dutch part)",
  slovakia: "Slovakia",
  slovenia: "Slovenia",
  "solomon-islands": "Solomon Islands",
  somalia: "Somalia",
  somaliland: "Republic of Somaliland",
  "south-africa": "South Africa",
  "south-georgia": "South Georgia and the South Sandwich Islands",
  "south-sudan": "South Sudan",
  spain: "Spain",
  "sri-lanka": "Sri Lanka",
  sudan: "Sudan (the)",
  suriname: "Suriname",
  "svalbard-and-jan-mayen": "Svalbard and Jan Mayen",
  sweden: "Sweden",
  switzerland: "Switzerland",
  syria: "Syrian Arab Republic(the)",
  taiwan: "Taiwan (Province of China)",
  tajikistan: "Tajikistan",
  tanzania: "Tanzania, the United Republic of",
  thailand: "Thailand",
  "timor-leste": "Timor-Leste",
  togo: "Togo",
  tokelau: "Tokelau",
  tonga: "Tonga",
  "trinidad-and-tobago": "Trinidad and Tobago",
  tunisia: "Tunisia",
  turkey: "Turkey",
  turkmenistan: "Turkmenistan",
  "turks-and-caicos-islands": "Turks and Caicos Islands (the)",
  tuvalu: "Tuvalu",
  uganda: "Uganda",
  ukraine: "Ukraine",
  "united-arab-emirates": "United Arab Emirates (the)",
  "united-kingdom": "United Kingdom of Great Britain and Northern Ireland (the)",
  "united-states-minor-outlying-islands": "United States Minor Outlying Islands (the)",
  "united-states-of-america": "United States of America (the)",
  uruguay: "Uruguay",
  uzbekistan: "Uzbekistan",
  vanuatu: "Vanuatu",
  venezuela: "Venezuela (Bolivarian Republic of)",
  vietnam: "Viet Nam",
  "virgin-islands-uk": "Virgin Islands (British)",
  "virgin-islands-us": "Virgin Islands (U.S.)",
  "wallis-and-futuna": "Wallis and Futuna",
  "western-sahara": "Western Sahara*",
  yemen: "Yemen",
  zimbabwe: "Zimbabwe",
  zambia: "Zambia"
} as const

export const territoriesISOA2 = {
  world: '',
  afghanistan: 'AF',
  albania: 'AL',
  algeria: 'DZ',
  'american-samoa': 'AS',
  andorra: 'AD',
  angola: 'AO',
  'anguilla-&-barbuda': 'AI',
  antartica: 'AQ',
  'antigua-and-barbuda': 'AG',
  argentina: 'AR',
  armenia: 'AM',
  aruba: 'AW',
  australia: 'AU',
  austria: 'AT',
  azerbaidjan: 'AZ',
  bahamas: 'BS',
  bahrain: 'BH',
  bangladesh: 'BD',
  barbados: 'BB',
  belarus: 'BY',
  belgium: 'BE',
  belize: 'BZ',
  benin: 'BJ',
  bermuda: 'BM',
  bhutan: 'BT',
  bolivia: 'BO',
  bonaire: 'BQ',
  'bosnia-and-herzegovina': 'BA',
  botswana: 'BW',
  'bouvet-island': 'BV',
  brazil: 'BR',
  'british-indian-ocean-territory': 'IO',
  brunei: 'BN',
  bulgaria: 'BG',
  burkina: 'BF',
  burundi: 'BI',
  'cabo-verde': 'CV',
  cambodia: 'KH',
  cameroon: 'CM',
  canada: 'CA',
  'cayman-islands': 'KY',
  'central-african-republic': 'CF',
  chad: 'TD',
  chile: 'CL',
  china: 'CN',
  'christmas-island': 'CX',
  'cocos-islands': 'CC',
  colombia: 'CO',
  comoros: 'KM',
  'congo-democratic-republic': 'CD',
  congo: 'CG',
  'cook-islands': 'CK',
  'costa-rica': 'CR',
  croatia: 'HR',
  cuba: 'CU',
  curacao: 'CW',
  cyprus: 'CY',
  'northern-cyprus': '-97',
  czech: 'CZ',
  'cote-d-ivoire': 'CI',
  denmark: 'DK',
  djibouti: 'DJ',
  dominica: 'DM',
  'dominican-republic': 'DO',
  ecuador: 'EC',
  egypt: 'EG',
  'el-salvador': 'SV',
  'equatorial-guinea': 'GQ',
  eritrea: 'ER',
  estonia: 'EE',
  eswatini: 'SZ',
  ethiopia: 'ET',
  'falkland-islands': 'FK',
  'faroe-islands': 'FO',
  fiji: 'FJ',
  finland: 'FI',
  france: 'FR',
  'french-guiana': 'GF',
  'french-polynesia': 'PF',
  'french-southern-territories': 'TF',
  gabon: 'GA',
  gambia: 'GM',
  georgia: 'GE',
  germany: 'DE',
  ghana: 'GH',
  gibraltar: 'GI',
  greece: 'GR',
  greenland: 'GL',
  grenada: 'GD',
  guadeloupe: 'GP',
  guam: 'GU',
  guatemala: 'GT',
  guernsey: 'GG',
  guinea: 'GN',
  'guinea-bissau': 'GW',
  guyana: 'GY',
  haiti: 'HT',
  'heard-island-and-mcdonald-islands': 'HM',
  'holy-see': 'VA',
  honduras: 'HN',
  'hong-kong': 'HK',
  hungary: 'HU',
  iceland: 'IS',
  india: 'IN',
  indonesia: 'ID',
  iran: 'IR',
  iraq: 'IQ',
  ireland: 'IE',
  'isle-of-man': 'IM',
  israel: 'IL',
  italy: 'IT',
  jamaica: 'JM',
  japan: 'JP',
  jersey: 'JE',
  jordan: 'JO',
  kazakhstan: 'KZ',
  kenya: 'KE',
  kiribati: 'KI',
  'north-korea': 'KP',
  'south-korea': 'KR',
  kosovo: '-98',
  kuwait: 'KW',
  kyrgyzstan: 'KG',
  laos: 'LA',
  latvia: 'LV',
  lebanon: 'LB',
  lesotho: 'LS',
  liberia: 'LR',
  libya: 'LY',
  liechtenstein: 'LI',
  lithuania: 'LT',
  luxembourg: 'LU',
  macao: 'MO',
  madagascar: 'MG',
  malawi: 'MW',
  malaysia: 'MY',
  maldives: 'MV',
  mali: 'ML',
  malta: 'MT',
  marshall: 'MH',
  martinique: 'MQ',
  mauritania: 'MR',
  mauritius: 'MU',
  mayotte: 'YT',
  mexico: 'MX',
  micronesia: 'FM',
  moldova: 'MD',
  monaco: 'MC',
  mongolia: 'MN',
  montenegro: 'ME',
  montserrat: 'MS',
  morocco: 'MA',
  mozambique: 'MZ',
  myanmar: 'MM',
  namibia: 'NA',
  nauru: 'NR',
  nepal: 'NP',
  netherlands: 'NL',
  'new-caledonia': 'NC',
  'new-zealand': 'NZ',
  nicaragua: 'NI',
  niger: 'NE',
  nigeria: 'NG',
  niue: 'NU',
  'norfolk-island': 'NF',
  'north-macedonia': 'MK',
  'northern-mariana-islands': 'MP',
  norway: 'NO',
  oman: 'OM',
  pakistan: 'PK',
  palau: 'PW',
  palestine: 'PS',
  panama: 'PA',
  papua: 'PG',
  paraguay: 'PY',
  peru: 'PE',
  philippines: 'PH',
  pitcairn: 'PN',
  poland: 'PL',
  portugal: 'PT',
  'puerto-rico': 'PR',
  qatar: 'QA',
  romania: 'RO',
  russia: 'RU',
  rwanda: 'RW',
  reunion: 'RE',
  'saint-barthelemy': 'BL',
  'saint-helena-ascension-and-tristan-da-cunha': 'SH',
  'saint-kitts-and-nevis': 'KN',
  'saint-lucia': 'LC',
  'saint-martin-french': 'MF',
  'saint-pierre-and-miquelon': 'PM',
  'saint-vincent-and-the-grenadines': 'VC',
  samoa: 'WS',
  'san-marino': 'SM',
  'sao-tome-and-principe': 'ST',
  'saudi-arabia': 'SA',
  senegal: 'SN',
  serbia: 'RS',
  seychelles: 'SC',
  'sierra-leone': 'SL',
  singapore: 'SG',
  'saint-martin-dutch': 'SX',
  slovakia: 'SK',
  slovenia: 'SI',
  'solomon-islands': 'SB',
  somalia: 'SO',
  somaliland: '-99',
  'south-africa': 'ZA',
  'south-georgia': 'GS',
  'south-sudan': 'SS',
  spain: 'ES',
  'sri-lanka': 'LK',
  sudan: 'SD',
  suriname: 'SR',
  'svalbard-and-jan-mayen': 'SJ',
  sweden: 'SE',
  switzerland: 'CH',
  syria: 'SY',
  taiwan: 'TW',
  tajikistan: 'TJ',
  tanzania: 'TZ',
  thailand: 'TH',
  'timor-leste': 'TL',
  togo: 'TG',
  tokelau: 'TK',
  tonga: 'TO',
  'trinidad-and-tobago': 'TT',
  tunisia: 'TN',
  turkey: 'TR',
  turkmenistan: 'TM',
  'turks-and-caicos-islands': 'TC',
  tuvalu: 'TV',
  uganda: 'UG',
  ukraine: 'UA',
  'united-arab-emirates': 'AE',
  'united-kingdom': 'GB',
  'united-states-minor-outlying-islands': 'UM',
  'united-states-of-america': 'US',
  uruguay: 'UY',
  uzbekistan: 'UZ',
  vanuatu: 'VU',
  venezuela: 'VE',
  vietnam: 'VN',
  'virgin-islands-uk': 'VG',
  'virgin-islands-us': 'VI',
  'wallis-and-futuna': 'WF',
  'western-sahara': 'EH',
  yemen: 'YE',
  zambia: 'ZM',
  zimbabwe: 'ZW',
  'aland-islands': 'AX'
} as const

export const territoriesISOA3 = {
  world: '',
  afghanistan: 'AFG',
  albania: 'ALB',
  algeria: 'DZA',
  'american-samoa': 'ASM',
  andorra: 'AND',
  angola: 'AGO',
  'anguilla-&-barbuda': 'AIA',
  antartica: 'ATA',
  'antigua-and-barbuda': 'ATG',
  argentina: 'ARG',
  armenia: 'ARM',
  aruba: 'ABW',
  australia: 'AUS',
  austria: 'AUT',
  azerbaidjan: 'AZE',
  bahamas: 'BHS',
  bahrain: 'BHR',
  bangladesh: 'BGD',
  barbados: 'BRB',
  belarus: 'BLR',
  belgium: 'BEL',
  belize: 'BLZ',
  benin: 'BEN',
  bermuda: 'BMU',
  bhutan: 'BTN',
  bolivia: 'BOL',
  bonaire: 'BES',
  'bosnia-and-herzegovina': 'BIH',
  botswana: 'BWA',
  'bouvet-island': 'BVT',
  brazil: 'BRA',
  'british-indian-ocean-territory': 'IOT',
  brunei: 'BRN',
  bulgaria: 'BGR',
  burkina: 'BFA',
  burundi: 'BDI',
  'cabo-verde': 'CPV',
  cambodia: 'KHM',
  cameroon: 'CMR',
  canada: 'CAN',
  'cayman-islands': 'CYM',
  'central-african-republic': 'CAF',
  chad: 'TCD',
  chile: 'CHL',
  china: 'CHN',
  'christmas-island': 'CXR',
  'cocos-islands': 'CCK',
  colombia: 'COL',
  comoros: 'COM',
  'congo-democratic-republic': 'COD',
  congo: 'COG',
  'cook-islands': 'COK',
  'costa-rica': 'CRI',
  croatia: 'HRV',
  cuba: 'CUB',
  curacao: 'CUW',
  cyprus: 'CYP',
  'northern-cyprus': '-97',
  czech: 'CZE',
  'cote-d-ivoire': 'CIV',
  denmark: 'DNK',
  djibouti: 'DJI',
  dominica: 'DMA',
  'dominican-republic': 'DOM',
  ecuador: 'ECU',
  egypt: 'EGY',
  'el-salvador': 'SLV',
  'equatorial-guinea': 'GNQ',
  eritrea: 'ERI',
  estonia: 'EST',
  eswatini: 'SWZ',
  ethiopia: 'ETH',
  'falkland-islands': 'FLK',
  'faroe-islands': 'FRO',
  fiji: 'FJI',
  finland: 'FIN',
  france: 'FRA',
  'french-guiana': 'GUF',
  'french-polynesia': 'PYF',
  'french-southern-territories': 'ATF',
  gabon: 'GAB',
  gambia: 'GMB',
  georgia: 'GEO',
  germany: 'DEU',
  ghana: 'GHA',
  gibraltar: 'GIB',
  greece: 'GRC',
  greenland: 'GRL',
  grenada: 'GRD',
  guadeloupe: 'GLP',
  guam: 'GUM',
  guatemala: 'GTM',
  guernsey: 'GGY',
  guinea: 'GIN',
  'guinea-bissau': 'GNB',
  guyana: 'GUY',
  haiti: 'HTI',
  'heard-island-and-mcdonald-islands': 'HMD',
  'holy-see': 'VAT',
  honduras: 'HND',
  'hong-kong': 'HKG',
  hungary: 'HUN',
  iceland: 'ISL',
  india: 'IND',
  indonesia: 'IDN',
  iran: 'IRN',
  iraq: 'IRQ',
  ireland: 'IRL',
  'isle-of-man': 'IMN',
  israel: 'ISR',
  italy: 'ITA',
  jamaica: 'JAM',
  japan: 'JPN',
  jersey: 'JEY',
  jordan: 'JOR',
  kazakhstan: 'KAZ',
  kenya: 'KEN',
  kiribati: 'KIR',
  'north-korea': 'PRK',
  'south-korea': 'KOR',
  kosovo: '-98',
  kuwait: 'KWT',
  kyrgyzstan: 'KGZ',
  laos: 'LAO',
  latvia: 'LVA',
  lebanon: 'LBN',
  lesotho: 'LSO',
  liberia: 'LBR',
  libya: 'LBY',
  liechtenstein: 'LIE',
  lithuania: 'LTU',
  luxembourg: 'LUX',
  macao: 'MAC',
  madagascar: 'MDG',
  malawi: 'MWI',
  malaysia: 'MYS',
  maldives: 'MDV',
  mali: 'MLI',
  malta: 'MLT',
  marshall: 'MHL',
  martinique: 'MTQ',
  mauritania: 'MRT',
  mauritius: 'MUS',
  mayotte: 'MYT',
  mexico: 'MEX',
  micronesia: 'FSM',
  moldova: 'MDA',
  monaco: 'MCO',
  mongolia: 'MNG',
  montenegro: 'MNE',
  montserrat: 'MSR',
  morocco: 'MAR',
  mozambique: 'MOZ',
  myanmar: 'MMR',
  namibia: 'NAM',
  nauru: 'NRU',
  nepal: 'NPL',
  netherlands: 'NLD',
  'new-caledonia': 'NCL',
  'new-zealand': 'NZL',
  nicaragua: 'NIC',
  niger: 'NER',
  nigeria: 'NGA',
  niue: 'NIU',
  'norfolk-island': 'NFK',
  'north-macedonia': 'MKD',
  'northern-mariana-islands': 'MNP',
  norway: 'NOR',
  oman: 'OMN',
  pakistan: 'PAK',
  palau: 'PLW',
  palestine: 'PSE',
  panama: 'PAN',
  papua: 'PNG',
  paraguay: 'PRY',
  peru: 'PER',
  philippines: 'PHL',
  pitcairn: 'PCN',
  poland: 'POL',
  portugal: 'PRT',
  'puerto-rico': 'PRI',
  qatar: 'QAT',
  romania: 'ROU',
  russia: 'RUS',
  rwanda: 'RWA',
  reunion: 'REU',
  'saint-barthelemy': 'BLM',
  'saint-helena-ascension-and-tristan-da-cunha': 'SHN',
  'saint-kitts-and-nevis': 'KNA',
  'saint-lucia': 'LCA',
  'saint-martin-french': 'MAF',
  'saint-pierre-and-miquelon': 'SPM',
  'saint-vincent-and-the-grenadines': 'VCT',
  samoa: 'WSM',
  'san-marino': 'SMR',
  'sao-tome-and-principe': 'STP',
  'saudi-arabia': 'SAU',
  senegal: 'SEN',
  serbia: 'SRB',
  seychelles: 'SYC',
  'sierra-leone': 'SLE',
  singapore: 'SGP',
  'saint-martin-dutch': 'SXM',
  slovakia: 'SVK',
  slovenia: 'SVN',
  'solomon-islands': 'SLB',
  somalia: 'SOM',
  somaliland: '-99',
  'south-africa': 'ZAF',
  'south-georgia': 'SGS',
  'south-sudan': 'SSD',
  spain: 'ESP',
  'sri-lanka': 'LKA',
  sudan: 'SDN',
  suriname: 'SUR',
  'svalbard-and-jan-mayen': 'SJM',
  sweden: 'SWE',
  switzerland: 'CHE',
  syria: 'SYR',
  taiwan: 'TWN',
  tajikistan: 'TJK',
  tanzania: 'TZA',
  thailand: 'THA',
  'timor-leste': 'TLS',
  togo: 'TGO',
  tokelau: 'TKL',
  tonga: 'TON',
  'trinidad-and-tobago': 'TTO',
  tunisia: 'TUN',
  turkey: 'TUR',
  turkmenistan: 'TKM',
  'turks-and-caicos-islands': 'TCA',
  tuvalu: 'TUV',
  uganda: 'UGA',
  ukraine: 'UKR',
  'united-arab-emirates': 'ARE',
  'united-kingdom': 'GBR',
  'united-states-minor-outlying-islands': 'UMI',
  'united-states-of-america': 'USA',
  uruguay: 'URY',
  uzbekistan: 'UZB',
  vanuatu: 'VUT',
  venezuela: 'VEN',
  vietnam: 'VNM',
  'virgin-islands-uk': 'VGB',
  'virgin-islands-us': 'VIR',
  'wallis-and-futuna': 'WLF',
  'western-sahara': 'ESH',
  yemen: 'YEM',
  zambia: 'ZMB',
  zimbabwe: 'ZWE',
  'aland-islands': 'ALA'
} as const

export const territoriesNUMCODE = {
  world: '',
  afghanistan: 4,
  albania: 8,
  algeria: 12,
  'american-samoa': 16,
  andorra: 20,
  angola: 24,
  'anguilla-&-barbuda': 660,
  antartica: 10,
  'antigua-and-barbuda': 28,
  argentina: 32,
  armenia: 51,
  aruba: 533,
  australia: 36,
  austria: 40,
  azerbaidjan: 31,
  bahamas: 44,
  bahrain: 48,
  bangladesh: 50,
  barbados: 52,
  belarus: 112,
  belgium: 56,
  belize: 84,
  benin: 204,
  bermuda: 60,
  bhutan: 64,
  bolivia: 68,
  bonaire: 535,
  'bosnia-and-herzegovina': 70,
  botswana: 72,
  'bouvet-island': 74,
  brazil: 76,
  'british-indian-ocean-territory': 86,
  brunei: 96,
  bulgaria: 100,
  burkina: 854,
  burundi: 108,
  'cabo-verde': 132,
  cambodia: 116,
  cameroon: 120,
  canada: 124,
  'cayman-islands': 136,
  'central-african-republic': 140,
  chad: 148,
  chile: 152,
  china: 156,
  'christmas-island': 162,
  'cocos-islands': 166,
  colombia: 170,
  comoros: 174,
  'congo-democratic-republic': 180,
  congo: 178,
  'cook-islands': 184,
  'costa-rica': 188,
  croatia: 191,
  cuba: 192,
  curacao: 531,
  cyprus: 196,
  'northern-cyprus': -97,
  czech: 203,
  'cote-d-ivoire': 384,
  denmark: 208,
  djibouti: 262,
  dominica: 212,
  'dominican-republic': 214,
  ecuador: 218,
  egypt: 818,
  'el-salvador': 222,
  'equatorial-guinea': 226,
  eritrea: 232,
  estonia: 233,
  eswatini: 748,
  ethiopia: 231,
  'falkland-islands': 238,
  'faroe-islands': 234,
  fiji: 242,
  finland: 246,
  france: 250,
  'french-guiana': 254,
  'french-polynesia': 258,
  'french-southern-territories': 260,
  gabon: 266,
  gambia: 270,
  georgia: 268,
  germany: 276,
  ghana: 288,
  gibraltar: 292,
  greece: 300,
  greenland: 304,
  grenada: 308,
  guadeloupe: 312,
  guam: 316,
  guatemala: 320,
  guernsey: 831,
  guinea: 324,
  'guinea-bissau': 624,
  guyana: 328,
  haiti: 332,
  'heard-island-and-mcdonald-islands': 334,
  'holy-see': 336,
  honduras: 340,
  'hong-kong': 344,
  hungary: 348,
  iceland: 352,
  india: 356,
  indonesia: 360,
  iran: 364,
  iraq: 368,
  ireland: 372,
  'isle-of-man': 833,
  israel: 376,
  italy: 380,
  jamaica: 388,
  japan: 392,
  jersey: 832,
  jordan: 400,
  kazakhstan: 398,
  kenya: 404,
  kiribati: 296,
  'north-korea': 408,
  'south-korea': 410,
  kosovo: -98,
  kuwait: 414,
  kyrgyzstan: 417,
  laos: 418,
  latvia: 428,
  lebanon: 422,
  lesotho: 426,
  liberia: 430,
  libya: 434,
  liechtenstein: 438,
  lithuania: 440,
  luxembourg: 442,
  macao: 446,
  madagascar: 450,
  malawi: 454,
  malaysia: 458,
  maldives: 462,
  mali: 466,
  malta: 470,
  marshall: 584,
  martinique: 474,
  mauritania: 478,
  mauritius: 480,
  mayotte: 175,
  mexico: 484,
  micronesia: 583,
  moldova: 498,
  monaco: 492,
  mongolia: 496,
  montenegro: 499,
  montserrat: 500,
  morocco: 504,
  mozambique: 508,
  myanmar: 104,
  namibia: 516,
  nauru: 520,
  nepal: 524,
  netherlands: 528,
  'new-caledonia': 540,
  'new-zealand': 554,
  nicaragua: 558,
  niger: 562,
  nigeria: 566,
  niue: 570,
  'norfolk-island': 574,
  'north-macedonia': 807,
  'northern-mariana-islands': 580,
  norway: 578,
  oman: 512,
  pakistan: 586,
  palau: 585,
  palestine: 275,
  panama: 591,
  papua: 598,
  paraguay: 600,
  peru: 604,
  philippines: 608,
  pitcairn: 612,
  poland: 616,
  portugal: 620,
  'puerto-rico': 630,
  qatar: 634,
  romania: 642,
  russia: 643,
  rwanda: 646,
  reunion: 638,
  'saint-barthelemy': 652,
  'saint-helena-ascension-and-tristan-da-cunha': 654,
  'saint-kitts-and-nevis': 659,
  'saint-lucia': 662,
  'saint-martin-french': 663,
  'saint-pierre-and-miquelon': 666,
  'saint-vincent-and-the-grenadines': 670,
  samoa: 882,
  'san-marino': 674,
  'sao-tome-and-principe': 678,
  'saudi-arabia': 682,
  senegal: 686,
  serbia: 688,
  seychelles: 690,
  'sierra-leone': 694,
  singapore: 702,
  'saint-martin-dutch': 534,
  slovakia: 703,
  slovenia: 705,
  'solomon-islands': 90,
  somalia: 706,
  somaliland: -99,
  'south-africa': 710,
  'south-georgia': 239,
  'south-sudan': 728,
  spain: 724,
  'sri-lanka': 144,
  sudan: 729,
  suriname: 740,
  'svalbard-and-jan-mayen': 744,
  sweden: 752,
  switzerland: 756,
  syria: 760,
  taiwan: 158,
  tajikistan: 762,
  tanzania: 834,
  thailand: 764,
  'timor-leste': 626,
  togo: 768,
  tokelau: 772,
  tonga: 776,
  'trinidad-and-tobago': 780,
  tunisia: 788,
  turkey: 792,
  turkmenistan: 795,
  'turks-and-caicos-islands': 796,
  tuvalu: 798,
  uganda: 800,
  ukraine: 804,
  'united-arab-emirates': 784,
  'united-kingdom': 826,
  'united-states-minor-outlying-islands': 581,
  'united-states-of-america': 840,
  uruguay: 858,
  uzbekistan: 860,
  vanuatu: 548,
  venezuela: 862,
  vietnam: 704,
  'virgin-islands-uk': 92,
  'virgin-islands-us': 850,
  'wallis-and-futuna': 876,
  'western-sahara': 732,
  yemen: 887,
  zambia: 894,
  zimbabwe: 716,
  'aland-islands': 248
} as const

export const territoriesFR = {
  world: '',
  afghanistan: 'Afghanistan (l\')',
  albania: 'Albanie (l\')',
  algeria: 'Algérie (l\')',
  'american-samoa': 'Samoa américaines (les)',
  andorra: 'Andorre (l\')',
  angola: 'Angola (l\')',
  'anguilla-&-barbuda': 'Anguilla',
  antartica: 'Antarctique (l\')',
  'antigua-and-barbuda': 'Antigua-et-Barbuda',
  argentina: 'Argentine (l\')',
  armenia: 'Arménie (l\')',
  aruba: 'Aruba',
  australia: 'Australie (l\')',
  austria: 'Autriche (l\')',
  azerbaidjan: 'Azerbaïdjan (l\')',
  bahamas: 'Bahamas (les)',
  bahrain: 'Bahreïn',
  bangladesh: 'Bangladesh (le)',
  barbados: 'Barbade (la)',
  belarus: 'Bélarus (le)',
  belgium: 'Belgique (la)',
  belize: 'Belize (le)',
  benin: 'Bénin (le)',
  bermuda: 'Bermudes (les)',
  bhutan: 'Bhoutan (le)',
  bolivia: 'Bolivie (État plurinational de)',
  bonaire: 'Bonaire, Saint-Eustache et Saba',
  'bosnia-and-herzegovina': 'Bosnie-Herzégovine (la)',
  botswana: 'Botswana (le)',
  'bouvet-island': 'Bouvet (l\'Île)',
  brazil: 'Brésil (le)',
  'british-indian-ocean-territory': 'Indien (le Territoire britannique de l\'océan)',
  brunei: 'Brunéi Darussalam (le)',
  bulgaria: 'Bulgarie (la)',
  burkina: 'Burkina Faso (le)',
  burundi: 'Burundi (le)',
  'cabo-verde': 'Cabo Verde',
  cambodia: 'Cambodge (le)',
  cameroon: 'Cameroun (le)',
  canada: 'Canada (le)',
  'cayman-islands': 'Caïmans (les Îles)',
  'central-african-republic': 'République centrafricaine (la)',
  chad: 'Tchad (le)',
  chile: 'Chili (le)',
  china: 'Chine (la)',
  'christmas-island': 'Christmas (l\'Île)',
  'cocos-islands': 'Cocos (les Îles)/ Keeling (les Îles)',
  colombia: 'Colombie (la)',
  comoros: 'Comores (les)',
  'congo-democratic-republic': 'Congo (la République démocratique du)',
  congo: 'Congo (le)',
  'cook-islands': 'Cook (les Îles)',
  'costa-rica': 'Costa Rica (le)',
  croatia: 'Croatie (la)',
  cuba: 'Cuba',
  curacao: 'Curaçao',
  cyprus: 'Chypre',
  'northern-cyprus': 'Chypre du Nord',
  czech: 'Tchéquie (la)',
  'cote-d-ivoire': 'Côte d\'Ivoire (la)',
  denmark: 'Danemark (le)',
  djibouti: 'Djibouti',
  dominica: 'Dominique (la)',
  'dominican-republic': 'dominicaine (la République)',
  ecuador: 'Équateur (l\')',
  egypt: 'Égypte (l\')',
  'el-salvador': 'El Salvador',
  'equatorial-guinea': 'Guinée équatoriale (la)',
  eritrea: 'Érythrée (l\')',
  estonia: 'Estonie (l\')',
  eswatini: 'Eswatini (l\')',
  ethiopia: 'Éthiopie (l\')',
  'falkland-islands': 'Falkland (les Îles)/Malouines (les Îles)',
  'faroe-islands': 'Féroé (les Îles)',
  fiji: 'Fidji (les)',
  finland: 'Finlande (la)',
  france: 'France (la)',
  'french-guiana': 'Guyane française (la )',
  'french-polynesia': 'Polynésie française (la)',
  'french-southern-territories': 'Terres australes françaises (les)',
  gabon: 'Gabon (le)',
  gambia: 'Gambie (la)',
  georgia: 'Géorgie (la)',
  germany: 'Allemagne (l\')',
  ghana: 'Ghana (le)',
  gibraltar: 'Gibraltar',
  greece: 'Grèce (la)',
  greenland: 'Groenland (le)',
  grenada: 'Grenade (la)',
  guadeloupe: 'Guadeloupe (la)',
  guam: 'Guam',
  guatemala: 'Guatemala (le)',
  guernsey: 'Guernesey',
  guinea: 'Guinée (la)',
  'guinea-bissau': 'Guinée-Bissau (la)',
  guyana: 'Guyana (le)',
  haiti: 'Haïti',
  'heard-island-and-mcdonald-islands': 'Heard-et-Îles MacDonald (l\'Île)',
  'holy-see': 'Saint-Siège (le)',
  honduras: 'Honduras (le)',
  'hong-kong': 'Hong Kong',
  hungary: 'Hongrie (la)',
  iceland: 'Islande (l\')',
  india: 'Inde (l\')',
  indonesia: 'Indonésie (l\')',
  iran: 'Iran (République Islamique d\')',
  iraq: 'Iraq (l\')',
  ireland: 'Irlande (l\')',
  'isle-of-man': 'Île de Man',
  israel: 'Israël',
  italy: 'Italie (l\')',
  jamaica: 'Jamaïque (la)',
  japan: 'Japon (le)',
  jersey: 'Jersey',
  jordan: 'Jordanie (la)',
  kazakhstan: 'Kazakhstan (le)',
  kenya: 'Kenya (le)',
  kiribati: 'Kiribati',
  'north-korea': 'Corée (la République populaire démocratique de)',
  'south-korea': 'Corée (la République de)',
  kosovo: 'Kosovo',
  kuwait: 'Koweït (le)',
  kyrgyzstan: 'Kirghizistan (le)',
  laos: 'Lao (la République démocratique populaire)',
  latvia: 'Lettonie (la)',
  lebanon: 'Liban (le)',
  lesotho: 'Lesotho (le)',
  liberia: 'Libéria (le)',
  libya: 'Libye (la)',
  liechtenstein: 'Liechtenstein (le)',
  lithuania: 'Lituanie (la)',
  luxembourg: 'Luxembourg (le)',
  macao: 'Macao',
  madagascar: 'Madagascar',
  malawi: 'Malawi (le)',
  malaysia: 'Malaisie (la)',
  maldives: 'Maldives (les)',
  mali: 'Mali (le)',
  malta: 'Malte',
  marshall: 'Marshall (les Îles)',
  martinique: 'Martinique (la)',
  mauritania: 'Mauritanie (la)',
  mauritius: 'Maurice',
  mayotte: 'Mayotte',
  mexico: 'Mexique (le)',
  micronesia: 'Micronésie (États fédérés de)',
  moldova: 'Moldova (la République de)',
  monaco: 'Monaco',
  mongolia: 'Mongolie (la)',
  montenegro: 'Monténégro (le)',
  montserrat: 'Montserrat',
  morocco: 'Maroc (le)',
  mozambique: 'Mozambique (le)',
  myanmar: 'Myanmar (le)',
  namibia: 'Namibie (la)',
  nauru: 'Nauru',
  nepal: 'Népal (le)',
  netherlands: 'Pays-Bas (les)',
  'new-caledonia': 'Nouvelle-Calédonie (la)',
  'new-zealand': 'Nouvelle-Zélande (la)',
  nicaragua: 'Nicaragua (le)',
  niger: 'Niger (le)',
  nigeria: 'Nigéria (le)',
  niue: 'Niue',
  'norfolk-island': 'Norfolk (l\'Île)',
  'north-macedonia': 'Macédoine du Nord (la)',
  'northern-mariana-islands': 'Mariannes du Nord (les Îles)',
  norway: 'Norvège (la)',
  oman: 'Oman',
  pakistan: 'Pakistan (le)',
  palau: 'Palaos (les)',
  palestine: 'Palestine, État de',
  panama: 'Panama (le)',
  papua: 'Papouasie-Nouvelle-Guinée (la)',
  paraguay: 'Paraguay (le)',
  peru: 'Pérou (le)',
  philippines: 'Philippines (les)',
  pitcairn: 'Pitcairn',
  poland: 'Pologne (la)',
  portugal: 'Portugal (le)',
  'puerto-rico': 'Porto Rico',
  qatar: 'Qatar (le)',
  romania: 'Roumanie (la)',
  russia: 'Russie (la Fédération de)',
  rwanda: 'Rwanda (le)',
  reunion: 'Réunion (La)',
  'saint-barthelemy': 'Saint-Barthélemy',
  'saint-helena-ascension-and-tristan-da-cunha': 'Sainte-Hélène, Ascension et Tristan da Cunha',
  'saint-kitts-and-nevis': 'Saint-Kitts-et-Nevis',
  'saint-lucia': 'Sainte-Lucie',
  'saint-martin-french': 'Saint-Martin (partie française)',
  'saint-pierre-and-miquelon': 'Saint-Pierre-et-Miquelon',
  'saint-vincent-and-the-grenadines': 'Saint-Vincent-et-les Grenadines',
  samoa: 'Samoa (le)',
  'san-marino': 'Saint-Marin',
  'sao-tome-and-principe': 'Sao Tomé-et-Principe',
  'saudi-arabia': 'Arabie saoudite (l\')',
  senegal: 'Sénégal (le)',
  serbia: 'Serbie (la)',
  seychelles: 'Seychelles (les)',
  'sierra-leone': 'Sierra Leone (la)',
  singapore: 'Singapour',
  'saint-martin-dutch': 'Saint-Martin (partie néerlandaise)',
  slovakia: 'Slovaquie (la)',
  slovenia: 'Slovénie (la)',
  'solomon-islands': 'Salomon (les Îles)',
  somalia: 'Somalie (la)',
  somaliland: 'Somaliland',
  'south-africa': 'Afrique du Sud (l\')',
  'south-georgia': 'Géorgie du Sud-et-les Îles Sandwich du Sud (la)',
  'south-sudan': 'Soudan du Sud (le)',
  spain: 'Espagne (l\')',
  'sri-lanka': 'Sri Lanka',
  sudan: 'Soudan (le)',
  suriname: 'Suriname (le)',
  'svalbard-and-jan-mayen': 'Svalbard et l\'Île Jan Mayen (le)',
  sweden: 'Suède (la)',
  switzerland: 'Suisse (la)',
  syria: 'République arabe syrienne (la)',
  taiwan: 'Taïwan (Province de Chine)',
  tajikistan: 'Tadjikistan (le)',
  tanzania: 'Tanzanie (la République-Unie de)',
  thailand: 'Thaïlande (la)',
  'timor-leste': 'Timor-Leste (le)',
  togo: 'Togo (le)',
  tokelau: 'Tokelau (les)',
  tonga: 'Tonga (les)',
  'trinidad-and-tobago': 'Trinité-et-Tobago (la)',
  tunisia: 'Tunisie (la)',
  turkey: 'Turquie (la)',
  turkmenistan: 'Turkménistan (le)',
  'turks-and-caicos-islands': 'Turks-et-Caïcos (les Îles)',
  tuvalu: 'Tuvalu (les)',
  uganda: 'Ouganda (l\')',
  ukraine: 'Ukraine (l\')',
  'united-arab-emirates': 'Émirats arabes unis (les)',
  'united-kingdom': 'Royaume-Uni de Grande-Bretagne et d\'Irlande du Nord (le)',
  'united-states-minor-outlying-islands': 'Îles mineures éloignées des États-Unis (les)',
  'united-states-of-america': 'États-Unis d\'Amérique (les)',
  uruguay: 'Uruguay (l\')',
  uzbekistan: 'Ouzbékistan (l\')',
  vanuatu: 'Vanuatu (le)',
  venezuela: 'Venezuela (République bolivarienne du)',
  vietnam: 'Viet Nam (le)',
  'virgin-islands-uk': 'Vierges britanniques (les Îles)',
  'virgin-islands-us': 'Vierges des États-Unis (les Îles)',
  'wallis-and-futuna': 'Wallis-et-Futuna',
  'western-sahara': 'Sahara occidental (le)*',
  yemen: 'Yémen (le)',
  zambia: 'Zambie (la)',
  zimbabwe: 'Zimbabwe (le)',
  'aland-islands': 'Åland(les Îles)'
} as const

export const months = {
  january: 'January',
  february: 'February',
  march: 'March',
  april: 'April',
  may: 'May',
  june: 'June',
  july: 'July',
  august: 'August',
  september: 'September',
  october: 'October',
  november: 'November',
  december: 'December'
} as const

export const budgetRange = {
  10000000: 'Less than $1 million',
  20000000: '$1 - 2 millions',
  35000000: '$2 - 3.5 millions',
  50000000: '$3.5 - 5 millions',
  100000000: '$5 - 10 millions',
  200000000: '$10 - 20 millions',
  999999999: 'More than $20 millions'
} as const;

export const staticModel = {
  budgetRange,
  contractStatus,
  contractType,
  legalDocumentTypes,
  legalRoles,
  subLicensorRoles,
  licenseStatus,
  distributionRightStatus,
  certifications,
  colors,
  contentType,
  crewRoles,
  directorCategory,
  genres,
  hostedVideoTypes,
  languages,
  medias,
  memberStatus,
  movieCurrencies,
  movieFormat,
  movieFormatQuality,
  movieLanguageTypes,
  premiereType,
  producerRoles,
  productionStatus,
  promotionalElementTypes,
  rating,
  scoring,
  orgActivity,
  soundFormat,
  stakeholderRoles,
  storeStatus,
  storeType,
  unitBox,
  cartStatus,
  organizationStatus,
  festival,
  months,
  screeningStatus,
  shootingPeriod,
  socialGoals,
  territories,
  territoriesISOA2,
  territoriesISOA3,
  territoriesNUMCODE,
  territoriesFR
};

export type StaticModel = typeof staticModel;
export type Scope = keyof StaticModel;
export type GetKeys<S extends Scope> = keyof StaticModel[S];
export type GetLabel<S extends Scope> = StaticModel[S][GetKeys<S>]
export type GetCode<S extends Scope> = GetKeys<S> | GetLabel<S>;

/** Check if the given value is a key of a scope */
export const isInKeys = (scope: Scope, givenValue: string) => {
  return (Object.keys(staticModel[scope])).map((key) => key).includes(givenValue);
}

/**
 * @param code
 * @param system
 */
export function getTerritoryFromGeoJson(
  code: string,
  system: 'iso_a3' | 'iso_a3' = 'iso_a3') {
  const territory = system === 'iso_a3'
    ? Object.keys(territoriesISOA3).find(i => i[system] === code.toUpperCase())
    : Object.keys(territoriesISOA2).find(i => i[system] === code.toUpperCase())
  if (!territory) {
    throw new Error(`Failed to retreive: ${code}.`);
  }
  return territory;;
}

/**
 * @param code
 * @param system
 */
export function getTerritorySlugFromGeoJson(code: string, system: 'iso_a3' | 'iso_a3' = 'iso_a3') {
  const territory = getTerritoryFromGeoJson(code, system);
  if (!territory) {
    throw new Error(`Failed to territory: ${code}.`);
  }
  return system === 'iso_a3' ? territory as TerritoryISOA3 : territory as TerritoryISOA2;
}

/**
 * @param code
 * @param system
 */
export function getTerritoryLabelFromGeoJson(code: string, system: 'iso_a3' | 'iso_a3' = 'iso_a3') {
  const territory = getTerritoryFromGeoJson(code, system);
  if (!territory) {
    throw new Error(`Failed to territory: ${code}.`);
  }
  return system === 'iso_a3' ? territoriesISOA3[territory] as TerritoryISOA3Value : territoriesISOA2[territory] as TerritoryISOA2Value;
}

/**
 * @param slug
 */
export function getISO3166TerritoryFromSlug(slug: Territory) {
  const territory = Object.keys(territories).find(i => i.toLowerCase() === slug.toLowerCase());
  if (!territory) {
    throw new Error(`Failed to territory: ${slug}.`);
  }
  return {
    [territory]: territory,
    'iso-a2': territoriesISOA2[territory],
    'iso-3': territoriesISOA3[territory],
    'numCode': territoriesNUMCODE[territory],
    'fr': territoriesFR[territory],
  }
}
